version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: furniture_store_db
    environment:
      POSTGRES_USER: furniture_user
      POSTGRES_PASSWORD: furniture_password
      POSTGRES_DB: furniture_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
