services:
  db:
    image: postgres:14
    container_name: furniture_store_db
    restart: always
    environment:
      POSTGRES_USER: furniture_user
      POSTGRES_PASSWORD: furniture_password
      POSTGRES_DB: furniture_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - furniture_network

  backend:
    build: ./backend
    container_name: furniture_store_backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://furniture_user:furniture_password@db:5432/furniture_store
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:80","http://localhost:8080"]
    ports:
      - "8000:8000"
    networks:
      - furniture_network

  frontend:
    build: ./frontend
    container_name: furniture_store_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - furniture_network

networks:
  furniture_network:
    driver: bridge

volumes:
  postgres_data:
